### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by colindaven** [sanger-pathogens/companion#57]
Hi, looks fascinating.

Nextflow installation worked fine for me without sudo rights.
 
However the docker pull required a "sudo docker pull xxxx", else I got an error message like this "dial unix /var/run/docker.sock: no such file or directory.
    Are you trying to connect to a TLS-enabled daemon without TLS?"

Ubuntu 15.10 System.

**Comment by satta** [comment]
Hi Colin,

can you confirm you are running a Docker daemon when you try doing the `docker pull` step?
It needs to be installed and running for any Docker operation, as well as Companion, to be successful. The error message seems to suggest it's not running.

You can access Docker without the need for sudo if your user is in the `docker` group. The posting https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo explains how to do that.

Just let me know if that helped.
Cheers, Sascha

**Comment by colindaven** [comment]
Thanks for the tip, apologies as I am very new to docker.

The whole pipeline seems very useful. What is your take on the effort required to extend it to additional use cases, eg annotation of plant genomes ? 
Would it be a case of cloning the dockerfile and adding/replacing pathogen specific data resources with plant data sources? I see you have nice documentation on extending some algorithms eg, augustus, with for example pathogene specific hint files, to new references. Would the effort required be a lot bigger to extend companion to plant genomes? 

Cheers,
Colin

**Comment by satta** [comment]
In general, there are little assumptions made about the kind of genome, most things are configurable in one way or another (e.g. weight files). Hints are created, for example, from reference protein alignments, so if there is a valid reference DB, then hints will be created. It's just a matter of preparing the reference DB from appropriate input.
However, the most problematic point here I see is that some of the tools used as part of the pipeline (e.g. RATT, ABACAS) are potential bottlenecks as they are not memory efficient as they have been specifically written for small (<100Mb) genomes in the first place. Also, some of the intermediate steps assume that one can just load all of the sequence into main memory. This means that for larger plant genomes such as wheat, they would probably need to be looked at before being usable on a desktop computer for a plant use case with a genome size exceeding, for example, that of *Arabidopsis* etc.
We haven't really tried this as it wasn't the focus of the project.

**Comment by colindaven** [comment]
Ok, thanks for the details. I will look into the pipeline in more detail if it is possible in principle. Memory issues should not be a huge problem if you have big mem servers (as we do) and do chromosome by chromosome or even scaffold or BAC analysis.  Tasks of this scale can be very common in the non-model plant world.

As you point out, plant genomes do tend to vary widely. You can however get a lot of mileage out of 0.1 to 1 GB plant genomes, even in the crops.

**Comment by satta** [comment]
Glad to be of help, closing this for now. Just let me know if there are any more questions.
